name: Kiledjian
favicon: null
layout_spectrum: 0.75499
typography_spectrum: 0.64907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9534011660143733
  lightness: 0.7156055353116244
  saturation: 0.7224536794237792
  rhythmicContrast: 0.6148369077127427
purpose: []
